/**
 * @file    lunar.c
 * @brief   Pure C lunar calendar implementation (1900–2100)
 */

#include "lunar.h"
#include <string.h>
#include <stdio.h>

/* =========================================================================
 * Compact lunar-year encoding  (generated by gen_lunar.py)
 *
 * Bits:  0-3  = leap month number (0 = no leap month)
 *        4-15 = months 1-12  (1 = 30 days, 0 = 29 days)
 *        16   = leap month size (1 = 30 days, 0 = 29 days)
 * ========================================================================= */
static const unsigned int lunarInfo[] = {
    0x00bd20, 0x007520, 0x00ea50, 0x00b2a0, 0x0064b0, 0x00a9b0, 0x00aa60, 0x0056a0,
    0x00b590, 0x00baa0, 0x007520, 0x00da50, 0x00b250, 0x00a4b0, 0x00a4b0, 0x002ad0,
    0x0056b0, 0x005b50, 0x00da90, 0x00e920, 0x00e920, 0x00d250, 0x00d2d0, 0x00a560,
    0x002b60, 0x00ad50, 0x006d40, 0x00ea90, 0x00f4a0, 0x00e920, 0x006a60, 0x0052b0,
    0x00a570, 0x009560, 0x00b5a0, 0x006d40, 0x007610, 0x007490, 0x00b130, 0x00a930,
    0x0052b0, 0x0051b0, 0x00aad0, 0x0056a0, 0x00da50, 0x00ba40, 0x00b490, 0x00d4b0,
    0x00a950, 0x00aad0, 0x005360, 0x00aad0, 0x00aca0, 0x005b20, 0x00da50, 0x00ea20,
    0x00d4a0, 0x005950, 0x00a970, 0x005560, 0x005750, 0x00ad50, 0x006d20, 0x007550,
    0x00ea50, 0x0064a0, 0x0064f0, 0x00a9b0, 0x00ada0, 0x0056a0, 0x00b690, 0x00bb20,
    0x00b520, 0x00b250, 0x00b2b0, 0x00a4b0, 0x00aab0, 0x002ad0, 0x0056d0, 0x005a90,
    0x00da90, 0x00d920, 0x00e950, 0x00d250, 0x00e4d0, 0x00a560, 0x002b60, 0x002f50,
    0x006d50, 0x00ea90, 0x00f520, 0x00e920, 0x00d260, 0x0052e0, 0x00a570, 0x00ad60,
    0x0035a0, 0x006d50, 0x00b690, 0x007490, 0x006930, 0x00a9b0, 0x0052b0, 0x00a5b0,
    0x00aae0, 0x0056a0, 0x00dd50, 0x00ba40, 0x00b490, 0x00d530, 0x00a950, 0x0052d0,
    0x0055d0, 0x00ab50, 0x00baa0, 0x005d20, 0x00da50, 0x00e8a0, 0x00d4a0, 0x00c950,
    0x00a9e0, 0x005560, 0x00ab50, 0x00ada0, 0x006d20, 0x007650, 0x007250, 0x0064b0,
    0x006570, 0x00cab0, 0x0055a0, 0x0056e0, 0x00b690, 0x00f520, 0x00b520, 0x00b250,
    0x00d0b0, 0x00a4b0, 0x004ab0, 0x002bb0, 0x005ad0, 0x00b6a0, 0x00daa0, 0x00d920,
    0x00ea50, 0x00d250, 0x00a550, 0x00a4d0, 0x004b60, 0x005b50, 0x006d20, 0x00ec90,
    0x00f920, 0x00e920, 0x00d260, 0x005160, 0x00a570, 0x004d60, 0x003650, 0x007550,
    0x007490, 0x0074b0, 0x006930, 0x00aab0, 0x0052b0, 0x00a5b0, 0x00aba0, 0x0056a0,
    0x00b650, 0x00baa0, 0x00b4a0, 0x00d950, 0x00a950, 0x0052d0, 0x0056d0, 0x00ab50,
    0x005aa0, 0x005d50, 0x00da50, 0x00d4a0, 0x00e4d0, 0x00c960, 0x00cce0, 0x005560,
    0x00ab50, 0x00ad20, 0x006d20, 0x00ea50, 0x0072a4, 0x0064b0, 0x006978, 0x004ab0,
    0x0055b0, 0x015566, 0x00b6a0, 0x007520, 0x00b954, 0x00b250, 0x00a8b0, 0x00a4f2,
    0x004ab0,
};

#define LUNAR_BASE_YEAR  1900
#define LUNAR_ENTRIES    (sizeof(lunarInfo) / sizeof(lunarInfo[0]))

/* Month names used by lunar_format() */
static const char *MONTH_NAMES[] = {
    "", "正月", "二月", "三月", "四月", "五月", "六月",
    "七月", "八月", "九月", "十月", "冬月", "腊月"
};
static const char *DAY_NAMES[] = {
    "", "初一", "初二", "初三", "初四", "初五", "初六", "初七", "初八", "初九", "初十",
    "十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十",
    "廿一", "廿二", "廿三", "廿四", "廿五", "廿六", "廿七", "廿八", "廿九", "三十"
};

/* ------------------------------------------------------------------ */
static int is_leap(int y) {
    return (y % 4 == 0 && y % 100 != 0) || (y % 400 == 0);
}

static int solar_days_in_month(int y, int m) {
    static const int mdays[] = { 0,31,28,31,30,31,30,31,31,30,31,30,31 };
    int d = mdays[m];
    if (m == 2 && is_leap(y)) d = 29;
    return d;
}

/* Days from 1900-01-31 (lunar 1900-01-01) to the given solar date. */
static int solar_to_offset(int y, int m, int d) {
    int total = 0;
    for (int i = LUNAR_BASE_YEAR; i < y; i++)
        total += is_leap(i) ? 366 : 365;
    for (int i = 1; i < m; i++)
        total += solar_days_in_month(y, i);
    total += d - 1;
    /* Subtract the base offset: 1900-01-31 = day 30 of 1900. */
    return total - 30;
}

/* Days in a lunar year (regular 12 months + possible leap month). */
static int lunar_year_days(int idx) {
    unsigned int info = lunarInfo[idx];
    int days = 0;
    for (int i = 0; i < 12; i++)
        days += (info & (1 << (4 + i))) ? 30 : 29;
    int leap = info & 0xF;
    if (leap)
        days += (info & (1 << 16)) ? 30 : 29;
    return days;
}

/* Days in a specific lunar month.  Set leap=1 for leap month. */
static int lunar_month_days(int idx, int month, int leap) {
    unsigned int info = lunarInfo[idx];
    if (leap)
        return (info & (1 << 16)) ? 30 : 29;
    return (info & (1 << (3 + month))) ? 30 : 29;
}

/* ------------------------------------------------------------------ */
int lunar_from_solar(int g_year, int g_month, int g_day, LunarDate *out) {
    if (g_year < LUNAR_BASE_YEAR || g_year > LUNAR_BASE_YEAR + (int)LUNAR_ENTRIES - 1)
        return -1;

    int offset = solar_to_offset(g_year, g_month, g_day);

    /* Find the lunar year */
    int ly = 0;
    int remain = offset;
    while (ly < (int)LUNAR_ENTRIES) {
        int yd = lunar_year_days(ly);
        if (remain < yd) break;
        remain -= yd;
        ly++;
    }

    out->year  = LUNAR_BASE_YEAR + ly;
    out->days_in_year = lunar_year_days(ly);
    out->leap  = 0;

    unsigned int info = lunarInfo[ly];
    int leap_month = info & 0xF;

    /* Walk through months */
    for (int m = 1; m <= 12; m++) {
        int md = lunar_month_days(ly, m, 0);
        if (remain < md) {
            out->month = m;
            out->day   = remain + 1;
            return 0;
        }
        remain -= md;

        /* Check leap month */
        if (leap_month == m) {
            int lmd = lunar_month_days(ly, m, 1);
            if (remain < lmd) {
                out->month = m;
                out->day   = remain + 1;
                out->leap  = 1;
                return 0;
            }
            remain -= lmd;
        }
    }

    return -1; /* should not reach here */
}

const char *lunar_format(const LunarDate *ld, char *buf, int bufsize) {
    const char *mn = (ld->month >= 1 && ld->month <= 12) ? MONTH_NAMES[ld->month] : "?";
    const char *dn = (ld->day >= 1 && ld->day <= 30) ? DAY_NAMES[ld->day] : "?";
    if (ld->leap)
        snprintf(buf, bufsize, "农历闰%s%s", mn, dn);
    else
        snprintf(buf, bufsize, "农历%s%s", mn, dn);
    return buf;
}
